language: node_js

node_js:
  - '5'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    - node_modules

before_install:
  - npm prune

script: npm run test-with-coverage

after_success: '[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ] && npm run coverage'
